entity: hajunsu
wandb_project_name: BCSDM
logdir: 'results/SE3/'
logger: 
  type: base
  endwith: ['@']
model:
  arch: deepovec_SE3
  total_out_dim: 12
  gamma: 0.01
  branch:
    arch: fc_vec
    in_dim: 6012 # demo length*12
    out_dim: 64
    l_hidden: [1024, 1024, 1024, 1024, 1024, 1024,]
    activation: ['relu', 'relu', 'relu', 'relu', 'relu', 'relu',]
    out_activation: 'linear'
  trunk:
    arch: fc_vec
    in_dim: 12
    out_dim: 64
    l_hidden: [1024, 1024, 1024, 1024, 1024, 1024,]
    activation: ['relu', 'relu', 'relu', 'relu', 'relu', 'relu',]
    out_activation: 'linear'
data:
  training:
    dataset: deepovec
    root: datasets/SE3_data.pt
    batch_size: 16384
    split: training
    shuffle: True
    num_workers: 0
  validation:
    dataset: deepovec
    root: datasets/SE3_data.pt
    batch_size: 16384
    split: validation
    shuffle: True
    num_workers: 0
  visualization:
    dataset: deepovec
    root: datasets/SE3_data.pt
    batch_size: 1
    split: visualization
    shuffle: True
    num_workers: 0
trainer: deepovec
training:
  type: deepovec
  n_epoch: 1000
  scheduler: cosine
  save_epochs: 100
  optimizer:
    name: 'adam'
    lr: 0.0001
  print_interval: 10
  val_interval: 10
  visualize_interval: 1000000000000
  visualization:
    type: [image]
    fig_size: [7, 7]
    axes_lim: [[-0.855, 0.855], [-0.855, 0.855], [-0.36, 1.19]] # franka workspace
    view_init: [30, 30]
    alpha: 0.2